spring:
  application:
    name: goblin
  profiles:
    active: @profileActive@

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.4.211:3306/quick_show
    username: root
    password: wangpeng123

    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  #单机配置
  redis:
    host: 49.234.4.211
    port: 6379
    #    password: 123456
    database: 0
    #redis连接池配置
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  #集群配置
#  redis:
#    password: 123456
#    cluster:
#      nodes: 10.255.144.115:7001,10.255.144.115:7002,10.255.144.115:7003,10.255.144.115:7004,10.255.144.115:7005,10.255.144.115:7006
#      max-redirects: 3


